[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { workspace = true, features = ["derive"] }
camino.workspace = true
xshell.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true