name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    name: Run pre-commit (in ci)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          components: clippy, rustfmt
          toolchain: 1.88.0

      - uses: Swatinem/rust-cache@a8b36e3f740d2ae4fa6e44a424a7b296af51cbef
        with:
          cache-on-failure: true
          cache-all-crates: true
          cache-workspace-crates: true
          cache-directories: "bin"

      - run: cargo xtask pre-commit
